### PR TITLE
[FIXED] RAFT subscriptions leak in failed connect

### LINKED ISSUE #1256: Memory increase in nats-streaming-server.exe on clusters with bad network connection
Using [clumsy](https://github.com/jagt/clumsy) it is possible to introduce a memory leak in the process by lagging/dropping packets between the nodes.

**Setup:**
Using the following config files, create a STAN cluster of 3 nodes.
[nats-streaming-server.zip](https://github.com/nats-io/nats-streaming-server/files/9021361/nats-streaming-server.zip)
These config files will host all 3 nodes on the localhost with ports for NATS (4223-4225), clustering (6223-6225) and monitoring (8223-8225)

**Reproduction:**
When all nodes are up and running, run [clumsy](https://github.com/jagt/clumsy) and introduce some lag on the local ports being used by NATS and clustering.
clumsy filter: 
tcp.DstPort == 4223 or tcp.SrcPort == 4223 or tcp.DstPort == 6223 or tcp.SrcPort == 6223 or tcp.DstPort == 4224 or tcp.SrcPort == 4224 or tcp.DstPort == 6224 or tcp.SrcPort == 6224 or tcp.DstPort == 4225 or tcp.SrcPort == 4225 or tcp.DstPort == 6225 or tcp.SrcPort == 6225

image
Leave it for about 1 minute.

Now disable the lag in clumsy and check the monitoring port of any of the nodes (eg: http://localhost:8223/connz?subs=1)
When you do the enable/disable lag step multiple times, you will see the internal RAFT subscriptions keep on growing.

The following is the output after doing this procedure a few times and giving it plenty of time to recover without the lag.

`{
  "server_id": "NAP776ZO2NVKAPJUWVSRTIXY7IWAMU2Y3OWKX3HMMDCGTEFVQADOXZW7",
  "now": "2022-06-30T15:53:40.2367406Z",
  "num_connections": 6,
  "total": 6,
  "offset": 0,
  "limit": 1024,
  "connections": [
    {
      "cid": 1,
      "kind": "Client",
      "type": "nats",
      "ip": "127.0.0.1",
      "port": 22074,
      "start": "2022-06-30T15:25:44.8472301Z",
      "last_activity": "2022-06-30T15:25:44.8522308Z",
      "rtt": "6.0282564s",
      "uptime": "27m55s",
      "idle": "27m55s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 0,
      "name": "_NSS-LetItLeak-send",
      "lang": "go",
      "version": "1.15.0"
    },
    {
      "cid": 2,
      "kind": "Client",
      "type": "nats",
      "ip": "127.0.0.1",
      "port": 22075,
      "start": "2022-06-30T15:25:44.8602196Z",
      "last_activity": "2022-06-30T15:26:04.1352763Z",
      "rtt": "6.0219175s",
      "uptime": "27m55s",
      "idle": "27m36s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 0,
      "name": "_NSS-LetItLeak-general",
      "lang": "go",
      "version": "1.15.0"
    },
    {
      "cid": 3,
      "kind": "Client",
      "type": "nats",
      "ip": "127.0.0.1",
      "port": 22076,
      "start": "2022-06-30T15:25:44.8623463Z",
      "last_activity": "2022-06-30T15:25:44.8630048Z",
      "rtt": "6.0363479s",
      "uptime": "27m55s",
      "idle": "27m55s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 0,
      "name": "_NSS-LetItLeak-acks",
      "lang": "go",
      "version": "1.15.0"
    },
    {
      "cid": 4,
      "kind": "Client",
      "type": "nats",
      "ip": "127.0.0.1",
      "port": 22077,
      "start": "2022-06-30T15:25:44.8635631Z",
      "last_activity": "2022-06-30T15:53:39.6621506Z",
      "rtt": "1ns",
      "uptime": "27m55s",
      "idle": "0s",
      "pending_bytes": 0,
      "in_msgs": 12136,
      "out_msgs": 11916,
      "in_bytes": 1243561,
      "out_bytes": 1840096,
      "subscriptions": 101,
      "name": "_NSS-LetItLeak-raft",
      "lang": "go",
      "version": "1.15.0",
      "subscriptions_list": [
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJf0",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKug",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nM0e",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNUt",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nIsS",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJVI",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMwu",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNGK",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNLB",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNjS",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNoJ",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJ2A",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nHXv",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nHmU",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJ71",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKRY",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nLIx",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMdU",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMiL",
        "_INBOX.dD3mavYy1UzCSkpJO7mlkr.*",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nZAG",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nI5u",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nIZ2",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nK88",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nLNo",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nHwC",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJGj",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nL9F",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNQ2",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nHJM",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nL4O",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nM5V",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMYd",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNtA",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKCz",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nHcm",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nIAl",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nIFc",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nIxJ",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJa9",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJyQ",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nLvn",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nGv5",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNZk",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nO7j",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nOHR",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMnC",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nHT4",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKWP",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKpp",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nLcN",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nLm5",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nH4n",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nH9e",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nIUB",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nInb",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJQR",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nLXW",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMFD",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMTm",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nGzw",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nOMI",
        "_STAN.raft.LetItLeak.join",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nHrL",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJBs",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nN6c",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNBT",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNeb",
        "raft.LetItLeak.Node1.LetItLeak.accept",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKMh",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKzX",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMOv",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nHOD",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nHhd",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJLa",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJoi",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nNy1",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nGqE",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMAM",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMK4",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nMs3",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nIdt",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nIPK",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJjr",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nK3H",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKHq",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKbG",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKg7",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nLE6",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nI13",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nLhE",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nOCa",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nLSf",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nIik",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nJtZ",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nKky",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nN1l",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nO2s",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nHEV",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nLqw",
        "raft.LetItLeak.Node1.LetItLeak.request._INBOX.dD3mavYy1UzCSkpJO7nIKT"
      ]
    },
    {
      "cid": 5,
      "kind": "Client",
      "type": "nats",
      "ip": "127.0.0.1",
      "port": 22078,
      "start": "2022-06-30T15:25:44.8647267Z",
      "last_activity": "2022-06-30T15:26:04.1352763Z",
      "rtt": "6.0219175s",
      "uptime": "27m55s",
      "idle": "27m36s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 0,
      "name": "_NSS-LetItLeak-raft_snap",
      "lang": "go",
      "version": "1.15.0"
    },
    {
      "cid": 6,
      "kind": "Client",
      "type": "nats",
      "ip": "127.0.0.1",
      "port": 22079,
      "start": "2022-06-30T15:25:44.8668179Z",
      "last_activity": "2022-06-30T15:25:44.8673651Z",
      "rtt": "6.0378265s",
      "uptime": "27m55s",
      "idle": "27m55s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 0,
      "name": "_NSS-LetItLeak-hb",
      "lang": "go",
      "version": "1.15.0"
    }
  ]
}`

### PR DESCRIPTION
**Pull request by kozlovic**
Resolves #1256

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/raft_transport.go [hunk 1]
```diff
@@ -238,7 +241,7 @@ func (n *natsConn) close(signalRemote bool) error {
 		return nil
 	}
 
-	if signalRemote {
+	if signalRemote && n.outbox != "" {
```
Comment (derekcollison) [inline server/raft_transport.go:244]: _EMPTY_

File: server/raft_transport.go [hunk 2]
```diff
@@ -493,6 +528,29 @@ func (n *natsStreamLayer) Accept() (net.Conn, error) {
 			peerConn.Close()
 			continue
 		}
+		if connect.Check != "" {
```
Comment (derekcollison) [inline server/raft_transport.go:531]: _EMPTY_

**Review by derekcollison — APPROVED** [review]
LGTM - nit on _EMPTY_ vs "" but you can ignore if that is not the practice here.
