### PR TITLE
[FIXED] Channel not deleted if sub not explicitly closed

### LINKED ISSUE #690: Channel not be deleted if subscription not explicitly closed
If a connection creates a subscription and the client exits without closing the connection, the server will ultimately close it after lack of HB response. However, this does not then trigger the delete channel timer.

### PR DESCRIPTION
**Pull request by kozlovic**
Trigger the channel delete timer (when max inactivity is set)
when a connection is closed (either explicitly or due to lack
of HB).

Resolves #690

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -3892,7 +3892,10 @@ func (s *StanServer) removeAllNonDurableSubscribers(client *client) {
 	subs := client.subs
 	clientID := client.info.ID
 	client.RUnlock()
-	var storesToFlush map[string]stores.SubStore
+	var (
+		storesToFlush map[string]stores.SubStore
```
Comment (derekcollison) [inline server/server.go]: If not critical performance wise just create empty storesToFlush like you do with the map below. Then you can eliminate nil checks.
