### PR TITLE
[FIXED] Clustering: erroneous "too many subscriptions per channel"

### LINKED ISSUE #809: Clustering: Version 0.14.0 produces erroneous "too many subscriptions per channel"
Version 0.14.0 has introduced a defect that would cause "too many subscriptions per channel" errors even though the actual number of subscriptions is below the limit.

cc @lazyshot

### PR DESCRIPTION
**Pull request by kozlovic**
This was introduced by #802. The server was replacing the sub's ID
after the call to CreateSub(), but that meant that DeleteSub() in
the underlying sub store would not find that subscription, which
will then cause it to report too many subscriptions after a while
because the removed subscriptions were not removed from their
internal map.
The approach in this PR is to make RaftSubStore completely bypass
the underlying SubStore. It should work with a mix of servers
of different versions.

Resolves #809

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: stores/raftstore.go [hunk 1]
```diff
@@ -93,6 +116,45 @@ func (s *RaftStore) DeleteClient(clientID string) error {
 // RaftSubStore methods
 ////////////////////////////////////////////////////////////////////////////
 
+// CreateSub implements the SubStore interface
+func (ss *RaftSubStore) CreateSub(sub *spb.SubState) error {
+	gss := &ss.genericSubStore
+
+	gss.Lock()
+	defer gss.Unlock()
```
Comment (derekcollison) [inline stores/raftstore.go]: Does perf matter here?

Comment (kozlovic) [reply stores/raftstore.go]: Not that many subs can be created per second, so not really. Plus, although as you know I am in favor of using `defer` sparingly, when you start to have multiple returns in the function, it starts to make sense.

Comment (derekcollison) [reply stores/raftstore.go]: Agree
