### PR TITLE
[FIXED] Incorrect number of subscriptions in /streaming/serverz

### LINKED ISSUE #819: Incorrect number of subscriptions in `streaming/serverz` when durables are resumed
The reported number of subscriptions increases every time a durable (queue or not) is restarted.

### PR DESCRIPTION
**Pull request by kozlovic**
Replaces the use of a variable that was supposed to be updated
on subscription create/remove. It was started to be a bit brittle.

Provide a function that computes the number of subscriptions
(including offline durables/queue durables).
This is a bit more costly than using the variable but will be
less prone to issues.

Resolves #819

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -742,6 +738,36 @@ type subSentAndAck struct {
...
+			// If this is a durable queue subscription and all members
+			// are offline, qsub.shadow will be not nil. Report this one.
+			if qsub.shadow != nil {
+				total++
+			}
+			qsub.RUnlock()
+		}
+		c.ss.RUnlock()
+	}
+	s.channels.RUnlock()
```
Comment (derekcollison) [inline server/server.go]: With cascading three tiers of locks, do we know we do not violate order somewhere else?

Comment (kozlovic) [reply server/server.go]: We do not. This is a well known order: the channel store is the main, then under this one we can take the channel subStore lock. Then we possibly go over queue states.
We do this on message delivery, monitor gathering of subs, etc..

Comment (derekcollison) [reply server/server.go]: ok
