### PR TITLE
[FIXED] Clustering: channel first/last sequence may fall to zero

### LINKED ISSUE #833: Clustering: still seeing cases where store first/last falls to 0
If a leader has a channel for which all messages have expired and no new message is sent on that channel, and a snapshot is taken and there is no raft log after that for this channel, a node that is restarted without state would restore from the snapshot but since all messages are expired, it would not persist anything in the channel's store.
If later this node becomes leader, and still no message is produced on this channel, and a snapshot is taken, it would persist first/last == 0 in the raft snapshot, which means that if yet another node is restarted without state, it would then get that there is no message in the channel and does not know that first sequence should be something else. So if/when that last node becomes leader later on, then it would start storing messages at sequence 1 for this channel, and all existing subscriptions would not receive messages until the first sequence in the channel reaches their last_sent value.

### PR DESCRIPTION
**Pull request by kozlovic**
This could happen if the leader took a snapshot while messages were
not yet expired, then a node is started without state and tries
to restore from this snapshot. If the messages have expired by then,
no message would be stored. If that node later did a snapshot itself,
it would persist in it the first/last being zero. If no message are
published and this node becomes leader, it would start storing
messages at the wrong sequence and would also send the bad snapshot
to other nodes.

Resolves #833

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/clustering.go [hunk 1]
```diff
@@ -477,18 +507,25 @@ func (r *raftFSM) Apply(l *raft.Log) interface{} {
...
-			if err == nil && lastSeq < msg.Sequence-1 {
-				err = s.raft.fsm.restoreMsgsFromSnapshot(c, lastSeq+1, msg.Sequence-1)
 			}
 			if err == nil {
 				_, err = c.store.Msgs.Store(msg)
 			}
 			if err != nil {
-				return fmt.Errorf("failed to store replicated message %d on channel %s: %v",
-					msg.Sequence, msg.Subject, err)
+				panic(fmt.Errorf("failed to store replicated message %d on channel %s: %v",
```
Comment (derekcollison) [inline server/clustering.go]: ok so this I am sure is on purpose since there is nothing we can do here. Just checking.

File: server/snapshot.go [hunk 2]
```diff
@@ -326,31 +337,35 @@ func (r *raftFSM) restoreChannelsFromSnapshot(serverSnap *spb.RaftSnapshot, inNe
...
+		// If we skip it (like we use to), then it is possible that this
+		// node misses some messages from the snapshot and will then start
+		// to apply remaining logs. It could even then become leader in
+		// the process with missing messages. So if we need to restore some
+		// messages and fail, keep trying until a leader is avail and
+		// able to serve this node.
+		for {
+			if err := r.restoreMsgsFromSnapshot(c, sc.First, sc.Last, false); err != nil {
+				s.log.Errorf("unable to restore messages, can't start until leader is available")
+				time.Sleep(time.Second)
```
Comment (derekcollison) [inline server/snapshot.go]: Is a whole second required here?

File: server/clustering.go (hunk 1 above)
Comment (kozlovic) [reply server/clustering.go]: Yes, it was a panic before, changed it (in master - no public release) to a return error, but it has to be a panic. RAFT has committed a log and applies it to the FSM (the streaming server code). If we fail to store in streaming store, we should bail and not continue (RAFT would simply move to next raft log). You would not even see the error since nothing is waiting/reporting on this apply future.

File: server/snapshot.go (hunk 2 above)
Comment (kozlovic) [reply server/snapshot.go]: Yes.. the restore failure is either because the leader is gone, or if it is a storage failure, it is likely not going to recover anyway. If it is a failure because leader is not running/gone, a new leader election takes some time, so no reason to rush this.

Comment (kozlovic) [reply server/snapshot.go]: Not to say that those are the only 2 reasons, there could be NATS communication issues (like sending the request fails due to disconnect and need to wait for reconnect), etc..

Comment (derekcollison) [reply server/snapshot.go]: Do we ever exit this or can a server look stuck sans the log messages? Should we bail after some point?

Comment (kozlovic) [reply server/snapshot.go]: No, this is an infinite loop. We could exit after few attempts but the point is that server will always be stuck at this step until a leader is able to service it. I can make it exit/panic after a certain number of attempts if you think it is better.

Comment (kozlovic) [reply server/snapshot.go]: And we want this server to either complete this step without errors or stay there (or exit, but the step can't be skipped, so will get back there on restart).

Comment (derekcollison) [reply server/snapshot.go]: Any management system would be waiting for it to exit to take action IMO. And if it was a health probe it would need to be able to signal to kill the server. I think we try for say 15-3o seconds then exit(-1).

**Comment by kozlovic** [comment]
@derekcollison I have pushed forced because I did a rebase from master to take the raft shutdown changes. But I kept a separate commit to ease the review. I can squash prior to merge. Commit to review would be this [one](https://github.com/nats-io/nats-streaming-server/pull/840/commits/fbc4114e0dece0a95966e346b65a24fe713d0ff7)

File: server/snapshot.go [hunk 3]
```diff
@@ -234,6 +246,27 @@ func (r *raftFSM) Restore(snapshot io.ReadCloser) (retErr error) {
 	r.Lock()
 	defer r.Unlock()
 
+	shouldSnapshot := false
+	defer func() {
+		if retErr == nil && shouldSnapshot {
```
Comment (derekcollison) [inline server/snapshot.go]: Doesn't this snapshot retErr here when defining the func? Meaning if you set it later it won't matter? May be remembering incorrectly.

File: server/snapshot.go [hunk 4]
```diff
@@ -234,6 +246,27 @@ func (r *raftFSM) Restore(snapshot io.ReadCloser) (retErr error) {
...
+				// s.raft.Snapshot() is actually s.raft.Raft.Snapshot()
+				// (our raft structure embeds Raft). But it is set after
+				// the call to NewRaft() - which invokes this function on
+				// startup. However, this runs under the server's lock, so
+				// simply grab the lock to ensure that Snapshot() will be
+				// able to execute.
+				// Also don't use startGoRoutine() here since it needs the
+				// server lock, which we already have.
+				s.mu.Lock()
+				s.raft.Snapshot().Error()
```
Comment (derekcollison) [inline server/snapshot.go]: Can't do in place correct?

File: server/snapshot.go [hunk 5]
```diff
@@ -325,43 +360,60 @@ func (r *raftFSM) restoreClientsFromSnapshot(serverSnap *spb.RaftSnapshot) error
...
 				break
 			}
 		}
+		if !ok {
+			err = fmt.Errorf("channel %q - unable to restore messages, aborting", sc.Channel)
+			s.log.Fatalf(err.Error())
+			// In tests, we use a "dummy" logger, so process will not exit
+			// (and we would not want that anyway), so make sure we return
+			// an error.
+			return false, err
```
Comment (derekcollison) [inline server/snapshot.go]: Can we even get here with Fatalf?

File: server/snapshot.go (hunk 3 above)
Comment (kozlovic) [reply server/snapshot.go]: No, what is deferred is the invocation of the function. So function will execute and evaluate whatever is inside. I have tested it works ok.

File: server/snapshot.go (hunk 4 above)
Comment (kozlovic) [reply server/snapshot.go]: meaning without go routine? if so no, since as I tried to explain, as part of the startup process we call NewRaft() (hashicorp raft constructor), which returns a Raft object that we assign to s.raft.Raft at the end of createRaftNode(). NewRaft() is the one invoking Restore() on startup (when there are local snapshots), so I can't call s.raft.Snapshot() until after the creation of the raft node has completed.

File: server/snapshot.go (hunk 5 above)
Comment (kozlovic) [reply server/snapshot.go]: Read comment above ;-). Yes, we can and do in all tests since our test logger does not exit. It would be bad if we did because all tests that trigger a fatalf would cause the test suite to stop (due to call to os.Exit()).

File: server/snapshot.go (hunk 3 above)
Comment (derekcollison) [reply server/snapshot.go]: ok
