### PR TITLE
[FIXED] Server is not rejecting `/` in channel names

### LINKED ISSUE #403: Server should reject `/` in channel names
The `/` symbol in channel names causes issues for FileStore implementation.
The server should reject channel names containing such character for all
store implementations to be consistent.

Related to #402

### PR DESCRIPTION
**Pull request by kozlovic**
This was a problem with FileStore implementation since channels
are not meant to translate into sub directories (but be flat).

The server now rejects channels containing `/`, regardless of
the store type being used.

Resolves #403

### CODE REVIEW

File: server/conf_test.go [hunk 1]
```diff
@@ -308,6 +308,7 @@ func TestParseWrongTypes(t *testing.T) {
 	expectFailureFor(t, "store_limits:{channels:{\"foo.*bar\":{}}}", wrongSubjErr)
 	expectFailureFor(t, "store_limits:{channels:{\"foo.>.>\":{}}}", wrongSubjErr)
 	expectFailureFor(t, "store_limits:{channels:{\"foo..bar\":{}}}", wrongSubjErr)
+	expectFailureFor(t, "store_limits:{channels:{\"foo/bar\":{}}}", wrongSubjErr)
```
Comment (petemiron) [inline server/conf_test.go]: For consistency with other changes, should these `wrongSubjErr`s be changed to `wrongChanErr`?
