### PR TITLE
[FIXED] Clustering: possible deadlock on sub/conn close

### LINKED ISSUE #812: Clustering: Possible deadlock when connection is closed while server sends messages
Typical stack trace will show a routine trying to replicate sent messages waiting because another go routine is performing the replication of a connection close and needs a lock held by the first go routine.
Example of the go routines showing the deadlock:
```
goroutine 6 [select]:
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).Apply(0xc0001078c0, 0xc000bd1360, 0x91, 0x91, 0x0, 0x0, 0x114a604)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/api.go:618 +0x1cf
github.com/nats-io/nats-streaming-server/server.(*StanServer).replicateSentAndAckSeqs(0xc00018c000, 0xc00058c000)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:3502 +0x175
github.com/nats-io/nats-streaming-server/server.(*StanServer).replicateSentOrAck(0xc00018c000, 0xc00058c000, 0x1, 0x57)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:3477 +0x119
github.com/nats-io/nats-streaming-server/server.(*StanServer).sendMsgToSub(0xc00018c000, 0xc00058c000, 0xc000449c70, 0xc00058c000, 0xc000449c70)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:3673 +0x896
github.com/nats-io/nats-streaming-server/server.(*StanServer).sendAvailableMessages(0xc00018c000, 0xc0005e5950, 0xc00058c000)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:4959 +0xc0
github.com/nats-io/nats-streaming-server/server.(*StanServer).processMsg(0xc00018c000, 0xc0005e5950)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:3205 +0x8f
github.com/nats-io/nats-streaming-server/server.(*StanServer).ioLoop(0xc00018c000, 0xc000024780)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:3891 +0x48a
created by github.com/nats-io/nats-streaming-server/server.(*StanServer).startIOLoop
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:3722 +0xcc


goroutine 85 [semacquire]:
sync.runtime_SemacquireMutex(0xc0005e5908, 0x2a57f00)
	/home/travis/.gimme/versions/go1.12.4.linux.amd64/src/runtime/sema.go:71 +0x3d
sync.(*RWMutex).Lock(0xc0005e5900)
	/home/travis/.gimme/versions/go1.12.4.linux.amd64/src/sync/rwmutex.go:98 +0x79
github.com/nats-io/nats-streaming-server/server.(*subStore).Remove(0xc0005e5900, 0xc0005e5950, 0xc000230000, 0xc0005e5900)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:947 +0x56
github.com/nats-io/nats-streaming-server/server.(*StanServer).removeAllNonDurableSubscribers(0xc00018c000, 0xc0002b25f0)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:4044 +0x224
github.com/nats-io/nats-streaming-server/server.(*StanServer).closeClient(0xc00018c000, 0xc000130010, 0xf, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:2961 +0xd3
github.com/nats-io/nats-streaming-server/server.(*raftFSM).Apply(0xc00000d3a0, 0xc0007e2120, 0x1d41d80, 0xc0000872c0)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/clustering.go:495 +0x6fb
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc000234060)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/fsm.go:57 +0x150
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).runFSM(0xc0001078c0)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/fsm.go:120 +0x33b
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc0001078c0, 0xc00016adc0)
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/state.go:146 +0x53
created by github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*raftState).goFunc
	/home/travis/gopath/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/state.go:144 +0x66
```
the first holds a lock and is waiting to Apply() a log to raft while the second is applying the close connection operation and that action required the lock held in the first go routine.

### PR DESCRIPTION
**Pull request by kozlovic**
There was a wrong assumption that calling raft.Apply() without
waiting on the future result would be non blocking. This is not
the case. RAFT internally uses go channels and there may be cases
when a receiver on a channel is busy and so sending to that channel
will block.

This is what was happening. RAFT would invoke the streaming server
code to apply the replication of a connection close. In this process
we try to remove subscriptions of that connection. This requires
the subStore lock. However, another go routine may be holding that
lock (and possibly subscription's lock, queue state, etc..) and
at the same time call raft.Apply() to replicate an aggregate of
subscription's sent/ack operations. In some cases this would actually
block, causing the deadlock.

Reworked handling of replication of sub's sent/ack events so that
this does not happen anymore.

Resolves #812

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/clustering_test.go [hunk 1]
```diff
@@ -5059,3 +5059,154 @@ func TestClusteringNoIncorrectMaxSubs(t *testing.T) {
...
+	pubConn.Close()
+
+	select {
+	case <-ch:
+	case <-time.After(5 * time.Second):
+		t.Fatalf("Did not receive all msgs")
+	}
+
+	waitForNumClients(t, s1, 0)
+	s1.Shutdown()
```
Comment (ColinSullivan1) [inline server/clustering_test.go]: nitpick - not necessary w/ defer above.
